### ISSUE TITLE
Missing utils.py file

### ISSUE THREAD

**Issue by KhalilBergaoui** [masoudpz/Ano-Graph#1]
Hi,

I was trying to reproduce some of Ano-Graph results but I noticed that the utils.py module is missing from the repo (necessary to run main.py completely).

Can you please add it ? Thank you !

**Comment by masoudpz** [comment]
thanks for your issue,
Please check it. It should be fixed now.

**Comment by KhalilBergaoui** [comment]
Hi,

I have noticed that you added the DGI modules, thank you ! 
However, I was referring to the utils.py file (that implements : get_objects()  and doit() methods). The file is called at line #7 in the main.py code.

Could you please add it as well ? Thanks !

**Comment by masoudpz** [comment]
I have added two missing functions to the utils.py, during some changes in detectron2 I should update other two functions.
