### ISSUE TITLE
Missing bb_intersection_over_union and get_objects in utils.py

### ISSUE THREAD

**Issue by NeeluMadanCreate** [masoudpz/Ano-Graph#2]
Hi,

I am trying to replicate the code. However, it seems two modules namely 'bb_intersection_over_union' and 'get_objects' are not defined in utils.py. Could you please add them as well?

Thanks...

**Comment by masoudpz** [comment]
Hi, thanks for your consideration. During some changes in Detectron2 we should change these functions. I am working on it, hope it will be fixed soon.
