### ISSUE TITLE
Runtime error : CUDA out of memory during loss.backward()

### ISSUE THREAD

**Issue by KhalilBergaoui** [masoudpz/Ano-Graph#3]
Hello, 

I tried to run your code on the entire Ped2 training set but I encounter the "Runtime error : CUDA out of memory during loss.backward(). Tried to allocate 32GiB .. ". It seems to me that this error is due to the large adjacency matrix obtained from the entire dataset of 2550 frames (as opposed to the 14 frames from your example in this repo). 

How did you solve this issue to train the model on Ped2 dataset using GPU ( GeForce GTX 1080 Ti has 11 Go of memory) ? Thanks a lot!

**Comment by masoudpz** [comment]
You can change the nms value in the object detection to manage the amount of ram that is needed for graph. Using nms you can control the amount of objects that have been detected in the video. (and in each frame)

**Comment by KhalilBergaoui** [comment]
@masoudpz Since your code is not completely provided, I experimented with code chunks from various sources which use a correct nms value. In fact it is easy to verify, for instance of the Ped2 dataset that the object detector functions well as it detects about 10-20 objects per frame which is expected since the scene is crowded. So for the entire training set (2550 frames) this gives an adjacency matrix of size NxN where N~ 20,000. This raises the memory error. You suggest however to control the amount of objects detected, but this solution is not scalable because it does not take into account the crowdedness and length of the training set (since you concatenate all the frames).

**Comment by masoudpz** [comment]
thanks for your comment. 
In this article, we use the interaction between the objects in the video to detect the anomaly, but by using the value of the nms, we can control the number of objects to some extent. Of course in crowded scene we need more Ram space, but during the test, we will deal with a limited number of frames which you can read in the table 5  in the "Effect of making local test time graphs" part.

**Comment by KhalilBergaoui** [comment]
Thank you for your quick reply! I totally agree with what you are saying however it is only specific to the test phase. 
In fact, for the training phase, you clearly explain in your article that you construct a global ST-graph and then use the summary vector to compute the loss function. The formula (5) in the article implies that you need to forward the entire training set in order to obtain the readout vector "s" and backpropagate the training error, which is the problem I encountered.  
So, could you please specify the size of the training adjacency matrix that you obtained for example when working with Ped2 and ShanghaiTech datasets ? It would help me know if there is something wrong in my object detection pipeline. Thanks !

**Comment by masoudpz** [comment]
Due to some changes in my hardware, now I do not have access to my test sources, I want to develop the source again with the last version of Detectron2. Let me update the source with new version asap and you can find test file.
