### ISSUE TITLE
About frame anomaly score ? (missing code)

### ISSUE THREAD

**Issue by KhalilBergaoui** [masoudpz/Ano-Graph#4]
Hello,

Could you please detail how you obtain a frame score given its objects' individual anomaly scores ?
I could not find details reading the paper and in your code the evaluation part is missing in order to reproduce the frame-AUC scores reported in the paper.

Thank you !

**Comment by masoudpz** [comment]
If there is at least one anomaly object in one frame, we set this frame as an anomaly frame.
